version: "3"

services:
        loconotion:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: loconotion:latest
                volumes:
                        - .:/app/dist
                restart: always
